config/routes.rb
Rails.application.routes.draw do
  resources :bars
  resources :matches
  get '' => 'home#index'
  get '/contact/new' => 'contact#new'
  post '/contact/new' => 'contact#record'
  get '/admin/contact/show' => 'contact#show'
  get '/admin/contact/detail/:id' => 'contact#detail'
  get '/admin/bars/index' => 'admin#bars'
  get '/admin/matches/index' => 'admin#matches'

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  has_and_belongs_to_many :matches
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_and_belongs_to_many :bars
  def self.search(search)
    where("home_team LIKE ? OR away_team LIKE ? OR league LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def bars
    @bars = Bar.all
  end

  def matches
    @matches = Match.all
    if params[:search]
      @matches = Match.search(params[:search]).order("created_at DESC")
    else
      @matches = Match.all.order("created_at DESC")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :set_bar, only: [:show, :edit, :update, :destroy]

  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
  end

  # GET /bars/new
  def new
    @bar = Bar.new
  end

  # GET /bars/1/edit
  def edit
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(bar_params)

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render :show, status: :created, location: @bar }
      else
        format.html { render :new }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bars/1
  # PATCH/PUT /bars/1.json
  def update
    respond_to do |format|
      if @bar.update(bar_params)
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { render :show, status: :ok, location: @bar }
      else
        format.html { render :edit }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar.destroy
    respond_to do |format|
      format.html { redirect_to admin_bars_index_url, notice: 'Bar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar
      @bar = Bar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_params
      params.require(:bar).permit(:bar_name, :bar_address, :website)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end

  def record
    Contact.create!(
      name: params[:name],
      bar: params[:bar],
      phone: params[:phone],
      email: params[:email],
      competition: params[:competition].join(', '),
      message: params[:message]
    )
  end

  def show
    @contacts = Contact.all
  end

  def detail
    @contact = Contact.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @days_of_week = []
    @matches_by_day = []
    for i in 0..6
      @matches_by_day << Match.where("DATE(match_time) = ?", Date.today+i)
      @days_of_week << (Date.today+i).strftime("%A")
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
    if params[:search]
      @matches = Match.search(params[:search]).order("created_at DESC")
    else
      @matches = Match.all.order("created_at DESC")
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @google_api_key = ENV["GMAP_API_KEY"]
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to admin_matches_index_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:home_team, :away_team, :league)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admin/bars.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2>Admin Bar Page</h2>
    <p><%= link_to 'Add New Bar', new_bar_path %></p>
  </header>
  <section class="wrapper style5">
    <div class="inner">

    <section>
      <table>
        <thead>
          <tr>
            <th>Bar</th>
            <th>Address</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @bars.each do |bar| %>
            <tr>
              <td><%= bar.bar_name %></td>
              <td><%= bar.bar_address %></td>
              <td><%= link_to 'View', bar %></td>
              <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
              <td><%= link_to 'Delete', bar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
</article>

app/views/admin/matches.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2>Admin Match Page</h2>
    <p><%= link_to 'Add New Match', new_match_path %></p>
  </header>
  <section class="wrapper style5">
    <div class="inner">

    <section>
      <table>
        <thead>
          <tr>
            <th>Home team</th>
            <th>Away team</th>
            <th>League</th>
            <th>Date</th>
            <th>Time</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @matches.each do |match| %>
            <tr>
              <td><%= match.home_team %></td>
              <td><%= match.away_team %></td>
              <td><%= match.league %></td>
              <td><%= match.match_time.strftime("%a, %b %d") %></td>
              <td><%= match.match_time.strftime("%H:%M") %></td>
              <td><%= link_to 'View', match %></td>
              <td><%= link_to 'Edit', edit_match_path(match) %></td>
              <td><%= link_to 'Delete', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

</article>

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bar_name %><br>
    <%= f.text_field :bar_name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :bar_address %><br>
    <%= f.text_area :bar_address %>
  </div>
  <br>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing Bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2>Bars</h2>
    <p>Find the perfect place for a pint</p>
  </header>
  <section class="wrapper style5">
    <div class="inner">

    <section>
      <table>
        <thead>
          <tr>
            <th>Bar</th>
            <th>Address</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @bars.each do |bar| %>
            <tr>
              <td><%= bar.bar_name %></td>
              <td><%= bar.bar_address %></td>
              <td><%= link_to 'View', bar %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
</article>

app/views/bars/new.html.erb
<article id="main">
  <header>
    <h2>Create a new bar</h2>
  <header>
  <section class="wrapper style5">
    <div class="inner">
      <section>

<%= render 'form' %>

    </section>
  </div>
</section>
</article>.

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2><%= @bar.bar_name %></h2>
  <header>
  <section class="wrapper style5">
    <div class="inner">
      <section>

        <h3>Bar Info</h3>
        <p>
          <strong>Address:</strong>
          <%= @bar.bar_address %>
        </p>

        <p>
          Visit the bar's <%= link_to 'website', @bar.website %>
        </p>

        <br>
        <p>
          <h3>Matches the bar is showing this week:</h3>
          <ul>
            <% @bar.matches.each do |match| %>
              <li id="main-cal"><%= match.home_team %> vs. <%=match.away_team %></li>
            <% end %>
          </ul>
        </p>
      </section>
    </div>
  </section>
</article>

app/views/contact/detail.html.erb
<article id="main">
  <header>
    <h2>Contact request</h2>
  <header>
  <section class="wrapper style5">
    <div class="inner">
      <section>
        <p>Bar:<%= @contact.bar %></p>
        <p>Contact Person:<%= @contact.name %></p>
        <p>Email:<%= @contact.email %></p>
        <p>Phone number:<%= @contact.phone %></p>
        <p>Message:<%= @contact.message %></p>
        <p>Competitions:<%= @contact.competition %></p>

      </section>
    </div>
  </section>
</article>

app/views/contact/new.html.erb
<article id="main">
  <header>
    <h2>Contact</h2>
    <p>Want to join the club?</p>
  </header>
  <section class="wrapper style5">
    <div class="inner">

      <section>
      	<h4>Sign up your bar</h4>
      	<form method="post" action="#">
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      		<div class="row uniform">
      			<div class="6u 12u$(xsmall)">
      				<input type="text" name="name" placeholder="Name" />
      			</div>
      			<div class="6u$ 12u$(xsmall)">
      				<input type="email" name="email" placeholder="Email" />
      			</div>
            <div class="6u 12u$(xsmall)">
              <input type="text" name="bar" placeholder="Bar" />
            </div>
            <div class="6u 12u$(xsmall)">
              <input type="text" name="phone" placeholder="Phone" />
            </div>
      			<div class="12u$">
      				<div class="select-wrapper">
      					<select multiple name="competition[]" id="multi-select">
      						<option value="">- Competitions you typically show -</option>
      						<option value="Premier League">Premier League</option>
      						<option value="La Liga">La Liga</option>
      						<option value="Bundesliga">Bundesliga</option>
      						<option value="Series A">Serie A</option>
                  <option value="Ligue 1">Ligue 1</option>
                  <option value="European Championships">European Championship</option>
                  <option value="Internationals">Internationals</option>
      					</select>
      				</div>
      			</div>
      			<div class="12u$">
      				<textarea name="message" placeholder="Enter your message" rows="6"></textarea>
      			</div>
      			<div class="12u$">
      				<ul class="actions">
      					<li><input type="submit" value="Send Message" class="special" /></li>
      					<li><input type="reset" value="Reset" /></li>
      				</ul>
      			</div>
      		</div>
      	</form>
      </section>

    </div>
  </section>
</article>

app/views/contact/record.html.erb
<article id="main">
	<header>
		<h2>Thank you <%= @name %>!</h2>
		<p>We have noted your request and will be in touch soon.</p>
	</header>
</article>

app/views/contact/show.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2>ADMIN CONTACT REQUESTS</h2>
  </header>
  <section class="wrapper style5">
    <div class="inner">
    <section>
      <table>
        <thead>
          <tr>
            <th>Bar Name</th>
            <th>Contact Person</th>
            <th>Email</th>
            <th>Phone</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody>
          <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.bar %></td>
              <td><%= contact.name %></td>
              <td><%= contact.email %></td>
              <td><%= contact.phone %></td>
              <td><%= link_to 'View', '/admin/contact/detail/' + contact.id.to_s %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
</article>

app/views/home/index.html.erb
<section id="banner">
  <div class="inner">
    <h2>MatchFinder</h2>
    <p>We help you find<br /> a local bar to watch<br /> your favorite sports.</p>
  </div>
  <a href="#one" class="more scrolly">Learn more</a>
  <br><br><br>
  <p>Looking for something specific?</p>
  <div id="search_bar" class="search">
      <%= form_tag(matches_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search matches" %>
      <br>
      <%= submit_tag "Search", :name => nil, :class => 'button special' %>
    <% end %>
  </div>
</header>
</section>

<article id="main">
<section id="one" class="wrapper style1 special">
    <div class="inner">
      <header class="major">
        <h2>This Week's Matches</h2>
        <div>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <section class="wrapper style5">
            <div class="inner">
            <table width="100%" id="home-cal">
              <thead>
              <tr width="(100/7)%">
                <% @days_of_week.each do |day| %>
                  <th>
                    <%= day %>
                  </th>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <col><col><col><col><col><col><col>
              <tr>
                <% @matches_by_day.each do |matches| %>
                  <td width="(100/7)%" id="center-text">
                    <% matches.each do |match| %>
                      <ul id="main-cal">
                        <li class="home-cal">
                          <%= link_to match.home_team + " vs. " + match.away_team, match %>
                        </li>
                      </ul>
                    <% end %>
                  </td>
                <% end %>
              </tr>
              </tbody>
            </table>
          </div>
          </section>
        </div>
  </div>
</section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatchFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

    <script>
    $(document).ready(function() {
      $(document).delegate('.open', 'click', function(event){
        $(this).addClass('oppenned');
        event.stopPropagation();
      })
      $(document).delegate('body', 'click', function(event) {
        $('.open').removeClass('oppenned');
      })
      $(document).delegate('.cls', 'click', function(event){
        $('.open').removeClass('oppenned');
        event.stopPropagation();
      });
    });
    </script>

  </head>

  <body>
    <div id="page-wrapper">
      <header id="header">
        <h1><%= link_to( image_tag("Logo.png"), '/', :id => "logo") %></h1>
        <nav id="nav">
          <ul>
            <li class="special">
              <a href="#menu" class="menuToggle"><span>Menu</span></a>
              <div id="menu">
                <ul>
                  <li><%= link_to 'Home', '/' %></li>
                  <li><%= link_to 'Bars', bars_path %></li>
                  <li><%= link_to 'Matches', matches_path %></li>
                  <li><%= link_to 'Contact', contact_new_path %></li>
                </ul>
              </div>
            </li>
          </ul>
        </nav>
      </header>

<%= yield %>

<footer id="footer">
  <ul class="icons">
    <li><a href="http://www.twitter.com" class="icon fa-twitter" id="twitter"><span class="label">Twitter</span></a></li>
  </ul>
  <ul class="copyright">
    <li>&copy; Nikki Parsons</li><li>Ironhack Final Project</li>
  </ul>
</footer>
</div>
</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home_team %><br>
    <%= f.text_field :home_team %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br>
    <%= f.text_field :away_team %>
  </div>
  <div class="field">
    <%= f.label :league %><br>
    <%= f.text_field :league %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2>Matches</h2>
    <p>Off to the match we go</p>
  </header>
  <section class="wrapper style5">
    <div class="inner">

    <section>
      <table>
        <thead>
          <tr>
            <th>Home team</th>
            <th>Away team</th>
            <th>League</th>
            <th>Date</th>
            <th>Time</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @matches.each do |match| %>
            <tr>
              <td><%= match.home_team %></td>
              <td><%= match.away_team %></td>
              <td><%= match.league %></td>
              <td><%= match.match_time.strftime("%a, %b %d") %></td>
              <td><%= match.match_time.strftime("%H:%M") %></td>
              <td><%= link_to 'View', match %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

<% if @matches.blank? %>
  <h4>There are no matches containing the term <%= params[:search] %>.</h4>
<% end %>

</article>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

<p id="notice"><%= notice %></p>

<article id="main">
  <header>
    <h2><%= @match.home_team %> vs. <%= @match.away_team %></h2>
  <header>
  <section class="wrapper style5">
    <div class="inner">
      <section>
      <h3>Match info</h3>
      <p>
        <strong>Home team:</strong>
        <%= @match.home_team %>
      </p>

      <p>
        <strong>Away team:</strong>
        <%= @match.away_team %>
      </p>

      <p>
        <strong>League:</strong>
        <%= @match.league %>
      </p>

      <p>
        <strong>Match Date:</strong>
        <%= @match.match_time.strftime("%A, %B %d at %H:%M") %>
      </p>
<br>
      <h3>Share</h3>
      <p>Want to invite some friends to watch the match?</p>

      <a class="twitter-share-button"
        href="https://twitter.com/intent/tweet?text=<%= u "Watching #{@match.home_team} vs. #{@match.away_team} later today. Anyone else up for it? \#MatchFinder " %>" data-size="large">
      Tweet</a>

      <br><br>

      <h3>Find a Bar to watch it</h3>

      <div id="map"></div>
          <script>
            function initMap() {
              var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 16,
              });
            // Try HTML5 geolocation.
              if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                  var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                  };

                  map.setCenter(pos);
                }, function() {
                  handleLocationError(true, map.getCenter());
                });
              } else {
                // Browser doesn't support Geolocation
                var barcelona = {lat: 41.387148, lng: 2.170122};
                  map.setCenter(barcelona);
              }

              <% @match.bars.each do |bar| %>

                  var markerImage = '/assets/football.png';

                  var marker = new google.maps.Marker({
                    position: {lat: <%= bar.latitude %>, lng: <%= bar.longitude %> },
                    map: map,
                    icon: markerImage
                  });

                  var contentString = '<div class="info-window">' +
                '<h3><%= bar.bar_name %></h3>' +
                '<div class="info-content">' +
                '<p><%= bar.bar_address %></p>' +
                '<p><%= link_to 'Bar details', bar %></p> '
                '</div>' +
                '</div>';

                  var infowindow = new google.maps.InfoWindow({
                      content: contentString,
                      maxWidth: 200
                  });

                  marker.addListener('click', function () {
                      infowindow.open(map, marker);
                  });
              <% end %>
              }

            function handleLocationError(browserHasGeolocation, pos) {
              infoWindow.setPosition(pos);
              infoWindow.setContent(browserHasGeolocation ?
                                    'Error: The Geolocation service failed.' :
                                    'Error: Your browser doesn\'t support geolocation.');
            }
          </script>

          <script async defer
              src="https://maps.googleapis.com/maps/api/js?key=<%= @google_api_key %>&callback=initMap">
          </script>

      <br><br>

      <p>
        <h3>Bars showing this match:</h3>
        <% if @match.bars.blank? %>
          <p>There are no bars currently scheduled to show this match.</p>
        <% end %>

        <% @match.bars.each do |bar| %>
          <ul>
            <li id="main-cal"><%= link_to bar.bar_name, bar %></li>
          </ul>
        <% end %>
      </p>

    </section>
  </article>